### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by ChrisBPB** [ArneVogel/concat#10]
I have ffmpeg installed and ffmpeg -version works etc so I know it is surely installed however I get

Combining parts

ffmpeg error
Deleting chunks
Deleting temp dir
All done!

Please output the ffmpeg err code so we can get useful information from it. Also in this event I feel like we should be prompted as to whether we want to delete the chunks or not - in this event I would much rather just have the chunks than nothing.

**Comment by ArneVogel** [comment]
Thats weird, the expected behaviour would be that it catches the output of ffmpeg and prints it when it get an ffmpeg error. On what OS are you working? Can you give me the output of running concat with `-debug`, mainly the ffmpeg command?

**Comment by ChrisBPB** [comment]
Windows 7, 64 bit

I tried it with a shorter vod because the other one was 6GB and I had already tried it 3 times and that's a lot of bandwidth. But it worked with the shorter one, perhaps the issue was trying to concat so many chunks

I also ran into an issue trying a very short vod (7 minutes) using -start="0 0 0" -end="full" and also tried -start="0 0 0" -end="0 1 0" - said the vod wasnt long enough for the end/start supplied

**Comment by ArneVogel** [comment]
Could you give me the command you are using? 

The ffmpeg error sounds a lot like [this issue](https://github.com/ArneVogel/concat/issues/2). Can you downloading ffmpeg from [here](https://ffmpeg.zeranoe.com/builds/) and pasting the ffmpeg.exe you find in the `bin` folder into the folder concat.exe is located in? This fixed it in the other issue.

**Comment by un0btanium** [comment]
Running into the same issue. The tool works great with short footage (< 1h), but once it is longer vods it always shows the ffmpeg error.

Furthermore, concat deletes all the downloaded files no matter what. It would be cool if it would not do that when an error occurs. so i dont have to download everything again and see it fail once more.

**Comment by Kirides** [comment]
ffmpeg throws "Too many open Files" error for me

See log: https://pastebin.com/nRcuXpvp

**Comment by ikonkere** [comment]
this is to do with your ulimit (at least on *nix, osx). Increasing it to elevated numbers (e.g. 8192) solved this for me.
