### ISSUE TITLE
osx binary packaging

### ISSUE THREAD

**Issue by ikonkere** [ArneVogel/concat#16]
What is this ***.dms** and how do i use it? the Internet refers to Amiga disk images (this can't be right), but i can't either open it with _unzip_ or mount it with _mount_. Can you just, you know, package it as a usual osx ***.dmg**? I'm too lazy to build the source every time it updates ;P.

**Comment by ArneVogel** [comment]
I am sorry but I have no idea what you are talking about :/

What is a .dms? What are you mounting? There has been no update for concat for nearly two months, what you have to build for every update?

**Comment by ikonkere** [comment]
When i click on "https://github.com/ArneVogel/concat/releases/download/v0.2.2/concat_mac" to download the release for OSX that's what is downloaded: "concat_mac.dms". It's not an archive, not an executable, so i can't run your distribution and have to build it manually.

**Comment by ArneVogel** [comment]
Ah I see. Unfortunately I don't have any computer that runs osx so I can't test this myself. I just trusted golang to compile it to osx the same way it compiled the windows binary on ubuntu. If you have any idea how to fix this I would greatly appreciate it.

**Comment by ikonkere** [comment]
So you were using cross-compiling? Well, i guess OSX prevails over golang shenanigans. I will close this issue then, building from source is obviously faster than you getting yourself a mac :).
