### ISSUE TITLE
OSX version segfaults on starts

### ISSUE THREAD

**Issue by Havner** [ArneVogel/concat#19]
Been successfully using windows version and decided to try OSX.

It segfaults on start.

```
$ concat_mac.dms 
Segmentation fault: 11
```

OSX 10.13.3

**Comment by ArneVogel** [comment]
This sounds like issue #16. 

Compiling the program yourself should create a working binary.

**Comment by ArneVogel** [comment]
Since I havent heard from any other of mac problems I am closing this.
