### ISSUE TITLE
FFmpeg error

### ISSUE THREAD

**Issue by Moremackles** [ArneVogel/concat#2]
When I try to do any video this happens, is there something I'm missing?
![error](https://user-images.githubusercontent.com/34537855/34097119-e7a4be38-e3a5-11e7-88ba-5618188ed8c6.PNG)

**Comment by ArneVogel** [comment]
Did you [download ffmpeg](https://www.ffmpeg.org/download.html) and put it in the directory that you are running concat from? Normally concat should output the error of ffmpeg if one occurs and because of the blank line I think concat couldn't find ffmpeg.

**Comment by Moremackles** [comment]
I did, I initally extracted the top level folder (the one with a bunch of files and folders inside of it) into the same folder that concat was in and tried it, but got the same error. After that I tried moving all of the ffmpeg stuff one folder up so concat was in with a bunch of misc files and folders but that did the same thing.

**Comment by Moremackles** [comment]
Ah, thank you. My fault but you might want to put that in the description on the front page, a lot of people are probably as dumb as I am :p
