### ISSUE TITLE
Concat stopped working properly. 

### ISSUE THREAD

**Issue by GasperTomsic** [ArneVogel/concat#20]
When you try to download vod with start and end timestamps, it downloads incorrect part of the vod. The downloader also doesn't work properly on your official site.

From what I tested its always a different delay. Maybe script doesn't calculate chunks properly? I think before (when concat was still working) twitch was sending 5 sec chunks and now they send 12 second chunk.

**Comment by ArneVogel** [comment]
I just checked with two vods and it worked normal for me. What vod did you try to download?

**Comment by GasperTomsic** [comment]
Hmmm, it still doesn't work. Did you download full vod or chunked? Maybe I should be clearer and specifiy the chunked part of the script doesn't work. Here is an example:

I tried to download CohhCarnage vod. 

vod link: https://www.twitch.tv/videos/239796789
From 01:00:45 to 01:20:45 in total 20 min long clip.
This example filled in official concat website. (Doesn't work in downloaded script either)
![concat_bug_1](https://user-images.githubusercontent.com/24734860/37565357-56c5af04-2aa8-11e8-9d14-c491bdd19bbb.JPG)

1:00:45 timestamp looks like this in CohhCarnage's vod section:
![concat_bug_2](https://user-images.githubusercontent.com/24734860/37565383-b9816f84-2aa8-11e8-95a5-c611ca94a162.JPG)

However this is the end result. As you can see the clip doesn't start anywhere even near the given timestamps and clip is 14 minutes long instead of 20.
![concat_bug_3](https://user-images.githubusercontent.com/24734860/37565393-f1b7abac-2aa8-11e8-9d94-752a653f811a.JPG)

Doesn't look like it happens in every clip. For example I just tried ThijsHS
https://www.twitch.tv/videos/239304303
from 3:10:00 to 3:20:00
and it worked properly. So something weird is going on.

**Comment by ArneVogel** [comment]
The problem seems to come from the faulty duration information of the m3u8 file. If you compile the newest version that should get fixed.

The old version trusted the chunk information in the header which fails with uneven durations of the chunks. In the vod the target duration was 6s and this is what the actuall duration of the chunks is.

> #EXTINF:3.468,
> 557.ts
> #EXTINF:5.632,
> 558.ts
> #EXTINF:5.868,
> 559.ts
> #EXTINF:5.600,
> 560.ts
> #EXTINF:5.315,
> 561.ts
> #EXTINF:4.567,

**Comment by GasperTomsic** [comment]
Just compiled the newest version and it works properly. 

Thanks you for the help.
