### ISSUE TITLE
FFMPEG Error?

### ISSUE THREAD

**Issue by PaddedGamer** [ArneVogel/concat#22]
I was able to use this program just fine for months. Now every time I attempt to use the program to download a vod, this happens. 

``` Duration: 02:54:06.61, start: 66.006000, bitrate: 4786 kb/s
  Program 1 
    Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 162 kb/s
    Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709), 1920x1080, 60 fps, 60 tbr, 90k tbn, 120 tbc
    Stream #0:2[0x102]: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x18b64a0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x18b64a0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to '236606799.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuvj420p, 1920x1080, q=2-31, 60 fps, 60 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 48000 Hz, stereo, 162 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help

ffmpeg error
Deleting chunks
Deleting temp dir
All done!
```

**Comment by ArneVogel** [comment]
Does this happen for all vods? Can you share one where it doesnt work and I will check it out.

**Comment by salgmachine** [comment]
yeah that seems to happen for any vod.. also ran into that issue:

`concat_ubuntu -vod 245833415 -end "06 19 00"`

**Comment by PaddedGamer** [comment]
Yes this happens to all vods. Terribly sorry about about the late reply. It should be noted that this issue did not appear until the date this issue was posted 14 days ago. It was working fine up until then.

**Comment by ArneVogel** [comment]
I cant seem to be able to reproduce the bug. The vod 245833415 works find for me. @PaddedGamer are you also on ubuntu? Have to tried to increase the ulimit? try `ulimit -n 8192`

**Comment by salgmachine** [comment]
huh will try that later. is there a specific Ubuntu version you recommend?

**Comment by ArneVogel** [comment]
Let me know if it works. Any ubuntu version should work fine.

**Comment by salgmachine** [comment]
huh increasing ulimit didn't work for me. i'm on ubuntu 14.04 
will continue testing with other ubuntu versions =)

**Comment by PaddedGamer** [comment]
I'm on Ubuntu 16.04 and not sure what's going on with it. I did use ulimit. But you see, it wouldn't be producing that error. Instead, it would be producing too many open files.

**Comment by ArneVogel** [comment]
should be fixed with newest release
