### ISSUE TITLE
Fails if downloading a larger VOD

### ISSUE THREAD

**Issue by itsmattkc** [ArneVogel/concat#23]
Encountered on Ubuntu 17.10 x86_64. When downloading a large VOD with a lot of chunks, concat's combining phase will sometimes fail with a "Too many open files/ffmpeg error" message. Technically this is a system issue, and can be worked around by increasing `ulimit -n` (default was 1024 and concat succeeded after setting it to 99999), however it'd be great if concat handled this case internally or if there was an option to not delete chunks after downloading so they could be concatenated manually.

**Comment by shinji257** [comment]
A patch has been recently merged that should fix this.  Are you able to try the current go code and see if it works?

**Comment by ArneVogel** [comment]
should be fixed with newest release
