### ISSUE TITLE
Memory access error

### ISSUE THREAD

**Issue by wiiarctus** [ArneVogel/concat#30]
With the latest version I get a "Memory access error". Twitch seems to have changed something, because with an older release of concat I don't get this error but instead it tries to find the VOD and the suggested quality option, but it doesn't work either.^^

**Comment by ArneVogel** [comment]
Can you post the full command you used? I tested downloading a vod and it worked fine with the newest release for me.

**Comment by wiiarctus** [comment]
Sure, I tried in multiple different ways, and a few months ago it worked fine for me too^^:
./concat_ubuntu -vod="123456789"
./concat_ubuntu -vod="123456789" -quality="chunked"
./concat_ubuntu -vod 123456789 -start 0 0 0
I tried the first two commands without the = and " too but with a space between -vod and the id.

**Comment by wiiarctus** [comment]
Okay I tried "./concat_ubuntu -vod=123456789 -end="full"" with the latest release and still get "Memory access error" and with v0.2.2 I get a update message "You are using an old version of concat. Check out https://github.com/ArneVogel/concat/releases/latest for the most recent version.

Call the program with -help for information on how to use it :^)" so something has to be wrong on my end? :/

**Comment by ArneVogel** [comment]
What distro are you using? Maybe try compiling it yourself.

**Comment by wiiarctus** [comment]
I'm using Debian 9 :)

**Comment by ArneVogel** [comment]
Yeah, thats probably the problem. Compiling the project yourself should hopefully fix the problem.

**Comment by wiiarctus** [comment]
And how can I do that? Sorry I'm a noob xD

**Comment by ArneVogel** [comment]
You have to install golang. When golang is installed you type.

go get github.com/arnevogel/concat

then go to the folder where it downloaded it and

go build

that compiles it.

**Comment by wiiarctus** [comment]
???
`main.go:4:2: cannot find package "bytes" in any of:
        /usr/local/go/bin/src/bytes (from $GOROOT)
        /root/go/src/bytes (from $GOPATH)
../../abiosoft/semaphore/semaphore.go:4:2: cannot find package "context" in any of:
        /usr/local/go/bin/src/context (from $GOROOT)
        /root/go/src/context (from $GOPATH)
main.go:5:2: cannot find package "encoding/json" in any of:
        /usr/local/go/bin/src/encoding/json (from $GOROOT)
        /root/go/src/encoding/json (from $GOPATH)
main.go:17:2: cannot find package "flag" in any of:
        /usr/local/go/bin/src/flag (from $GOROOT)
        /root/go/src/flag (from $GOPATH)
logging.go:4:2: cannot find package "fmt" in any of:
        /usr/local/go/bin/src/fmt (from $GOROOT)
        /root/go/src/fmt (from $GOPATH)
main.go:9:2: cannot find package "io/ioutil" in any of:
        /usr/local/go/bin/src/io/ioutil (from $GOROOT)
        /root/go/src/io/ioutil (from $GOPATH)
main.go:10:2: cannot find package "net/http" in any of:
        /usr/local/go/bin/src/net/http (from $GOROOT)
        /root/go/src/net/http (from $GOPATH)
logging.go:5:2: cannot find package "os" in any of:
        /usr/local/go/bin/src/os (from $GOROOT)
        /root/go/src/os (from $GOPATH)
main.go:13:2: cannot find package "os/exec" in any of:
        /usr/local/go/bin/src/os/exec (from $GOROOT)
        /root/go/src/os/exec (from $GOPATH)
main.go:12:2: cannot find package "path/filepath" in any of:
        /usr/local/go/bin/src/path/filepath (from $GOROOT)
        /root/go/src/path/filepath (from $GOPATH)
main.go:7:2: cannot find package "regexp" in any of:
        /usr/local/go/bin/src/regexp (from $GOROOT)
        /root/go/src/regexp (from $GOPATH)
main.go:18:2: cannot find package "runtime" in any of:
        /usr/local/go/bin/src/runtime (from $GOROOT)
        /root/go/src/runtime (from $GOPATH)
main.go:14:2: cannot find package "strconv" in any of:
        /usr/local/go/bin/src/strconv (from $GOROOT)
        /root/go/src/strconv (from $GOPATH)
main.go:15:2: cannot find package "strings" in any of:
        /usr/local/go/bin/src/strings (from $GOROOT)
        /root/go/src/strings (from $GOPATH)
../../abiosoft/semaphore/semaphore.go:5:2: cannot find package "sync" in any of:
        /usr/local/go/bin/src/sync (from $GOROOT)
        /root/go/src/sync (from $GOPATH)
../../abiosoft/semaphore/semaphore.go:6:2: cannot find package "time" in any of:
        /usr/local/go/bin/src/time (from $GOROOT)
        /root/go/src/time (from $GOPATH)`

**Comment by wiiarctus** [comment]
So I compiled it on my PC with Win10 and still I get "Call the program with -help for information on how to use it :^)" when using "concat.exe -vod=123456789 -end="full"" :(

**Comment by ArneVogel** [comment]
You are replacing 123456789 with the actual vod id right?

**Comment by wiiarctus** [comment]
Yes I did replace it. I was able to get it compiling on my Debian server somehow now, and it works just fine!^^ Thank you for your help :D
