### ISSUE TITLE
ffmpeg location input

### ISSUE THREAD

**Issue by Wingzzzzz** [ArneVogel/concat#31]
As many may not include ffmpeg in build path
or put concat in the same folder as ffmpeg executable,
i suggest provide location input.
E.g. -ffmepg "D;/ffmpeg/bin/ffmpeg.exe"

**Comment by Wiethoofd** [comment]
Also the error message when ffmpeg is not available could be clearer.

Currently: `Could not find ffmpeg, make sure to have ffmpeg avaliable on your system.`
Suggestion: `Could not find ffmpeg, place it in the same location as the concat executable or specify location with the -ffmpeg option.`

Also update the readme.md to make that clear, saves attempts at install on Windows if it is as simple as extracting ffmpeg.exe to the right folder.

**Comment by shilangyu** [comment]
Does this still apply? Im pretty sure concat now searches for PATH executable

**Comment by ArneVogel** [comment]
Yes, concat should search for PATH executables. At least thats what I am experiencing on linux.

**Comment by shilangyu** [comment]
I'm on windows and cannot reproduce this error, concat is searching for PATH ffmpeg not if it's in the same folder
