### ISSUE TITLE
[Feature Request] Loading bar + file sizes in console

### ISSUE THREAD

**Issue by PointyDev** [ArneVogel/concat#34]
Hey there,

Would like to request a feature similar to npm's progress bar when handling downloads, see the gif below:

![https://pointy.needs-to-s.top/09d29b.gif](https://pointy.needs-to-s.top/09d29b.gif)

My reasoning behind this is the fact that a series of dots appearing isn't exactly the most helpful progress indicator, and only really serves as an indicator that the tool is still responding.

Thanks,
Elliott

**Comment by MCOfficer** [comment]
a simpler solution would be to simply give the number of finished and total chunks. i'm not fluent in go, but from looking at the code, both numbers appear to be known.

**Comment by MCOfficer** [comment]
nice. you might want to PR this back here, in case this repo becomes active again.

**Comment by ArneVogel** [comment]
@Kirides yeah as MCOfficer mentioned feel free to create a pull request. Most people download the tool from this repo so if you want with a pull request I can create new binaries with your changed incorporated.

**Comment by Kirides** [comment]
@ArneVogel my fork drifted a little from your work :/

How would you like me to PR? (With all of my current changes? Just the parts that are required?)

**Comment by shilangyu** [comment]
Added a loading bar together with doneChunks/totalChunks indicator
