### ISSUE TITLE
Resume downloads

### ISSUE THREAD

**Issue by yonilerner** [ArneVogel/concat#44]
Ive been trying for the last few hours to download a specific VOD, and due to its size and the instability of my internet connection, I can never get it to complete. I have all these temporary files downloaded, but restarting the download doesnt seem to make use of them. 

What would it take to implement resume functionality? I've never used Go before, but I would be happy to try implementing it if I was pointed in the right direction.

**Comment by ArneVogel** [comment]
Thanks for the implementation
