### ISSUE TITLE
Running on MacOS (solution)

### ISSUE THREAD

**Issue by dsiher** [ArneVogel/concat#47]
I was trying to run concat and ran into the same problems as #36 and #16 but found out the fix.

When downloading the file, if using Safari, the extension will sometimes be switched from no extension to a .dms file, so you have to remove the extension.

Once you get the file without an extension, you have to run `chmod +x ./concat_mac` in terminal to associate the file as a unix executable or else terminal won't allow you to run it.

After that you should be able to run the file using ./concat_mac from terminal and continue to use the functionality as stated in the README.

**Comment by ArneVogel** [comment]
Thanks. I have updated the readme with your fix.
