### ISSUE TITLE
-start and -end is not accurate

### ISSUE THREAD

**Issue by johnguibas** [ArneVogel/concat#48]
Concat's -start and -end flags are not working correctly for me. When I run the command `./concat_linux -vod="383949775" -start="1 7 15" -end="1 7 37"`, I get a video that is 35 seconds long when it should in fact be 22. I have also compared it with the actual VOD at twitch.tv/videos/383949775 and the trimming is indeed wrong. It looks like it does it from "1 7 5" to "1 7 40" instead (in the actual VOD timestamp).

I am running concat on Ubuntu 16.04 and am using the latest version.

This is a great project and I would really appreciate any input from other contributors, I will also look into the code myself.

**Comment by ArneVogel** [comment]
When the video is downloaded its downloaded in chunks that vary in length. These chunks are normally between 5-10 seconds. The start and end flags are only as accurate as its possible with the length of those chunks. 

Assuming the chunks are 10s long and you specify to download from "0 0 14" to "0 1 55" the downloader would round up and down to the nearest 10s. It would actually download from "0 0 10" to "0 2 0".
