### ISSUE TITLE
[Bug] No available quality options found / This API has been removed

### ISSUE THREAD

**Issue by breimers** [ArneVogel/concat#59]
## Bug Report

Issue: Cannot download videos.

Command: `concat -vod="123456789"`

Expected: begins a Twitch video download. 

Actual: 
```
user@host:~$ concat -vod="482122315"
Contacting Twitch Server
Couldn't find quality: chunked
No available quality options found
```
Test video-ids: `["482122315", "7695281", "378008253", "473298056"]`

Test Environments:
 - Docker-container (from python) 
 - CircleCI (docker + ci utils)
 - Desktops (Pop_os!, Ubuntu)

Other info:
I saw a similar issue with pytube when YouTube changed some of their back-end stream options. It is likely this is the result of a Twitch update, considering your app has been working great for the past few months.

I wondered if the API was broken so I tried this: 
`curl https://api.twitch.tv/api/vods/482122315/access_token?client_id=aokchnui2n8q38g0vezl9hq6htzy4c`

And the repsonse was not great:
`{"error":"Gone","status":410,"message":"this API has been removed."}`

**Comment by ArneVogel** [comment]
I tried downloading the videos you mentioned and didn't encounter the problem you described. Can you try again?

**Comment by breimers** [comment]
> I tried downloading the videos you mentioned and didn't encounter the problem you described. Can you try again?

Confirm I am having the same issue on both my Desktop (Pop_Os!) and on a Kubernetes pod.

I am using the latest release binary, as we don't have the pod(s) set up for Go.

**Comment by jtguibas** [comment]
@breimers @ArneVogel I think this has something to do with the Twitch API going down once in a while. I've encountered this issue but it goes away after a few hours.
