### ISSUE TITLE
Couldn't find quality: chunked

### ISSUE THREAD

**Issue by yojosee** [ArneVogel/concat#60]
Issue: Cannot download videos , i try new vods and vods that had already been downloaded and it doesn't work.
The Error:
"Couldn't find quality: chunked"

Environments: Windows 10 64 bits

**Comment by yojosee** [comment]
now it seems to work apparently it's a twitch issue i don't know :S

**Comment by breimers** [comment]
I'm the same issue. I created a bug report. 

You can add here --> https://github.com/ArneVogel/concat/issues/59
